gluonhq/scenebuilder

- app/src/main/java/com/oracle/javafx/scenebuilder/app/i18n/I18N.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/i18n/I18N.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/i18n/I18NControl.java
Fixes #186
Implements custom control
When reading unicode escaped strings, custom control might be needed.
https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle
> Issue #186: Fix i18n feature

- app/src/main/java/com/oracle/javafx/scenebuilder/app/DocumentWindowController.java
- app/src/main/resources/com/oracle/javafx/scenebuilder/app/DocumentWindow.fxml
- app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp.properties
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/ImportWindowController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/LibraryPanelController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/LibraryUtil.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/LibraryDialogController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/LibraryDialogListCell.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/LibraryDialogListItem.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/UserLibrary.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/util/FolderExplorer.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/util/JarExplorer.java
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/editor/panel/library/LibraryDialog.fxml
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties
This PR adds a long waited (by me) feature, that enables the user to add a folder (in particular, root folders with classes) to the custom components library.
Users can add as many folders as they want.
After adding one folder to the library, that one is used as the root for loading classes in all its subfolders, and components that were able to be loaded are added to the "Custom" library panel, as if they loaded from a jar.
Bonus: the library label updates its text during scanning, so it is evident to users that a maybe long process is running..
The main advatange of this PR, is that a developer can add a "bin" folder from their running Eclipse/IDEA to the library manager and have the custom components loaded into SB without the need to create and publish a jar to the library directory …
> UserLibrary: feature for adding folders to library

- .gitignore
The gitignore file has a typo that causes Eclipse project settings files to be tracked.
> Fix typo in gitignore file

- .github/workflows/build.yml
Currently the build workflow stucks indefinitely as tests needs a DISPLAY on Linux systems to run, This change adds vncserver to enable display on linux environments.
> Add display to build workflow before running tests

- .github/workflows/mac.yml
Fixes failing "Upload to AWS S3" step in mac workflow
> GA: Add S3_PATH to environment variables

- app/build.gradle
The standard MSI installer requests administrative privileges. The per-user-install doesn't.
Furthermore the new configuration allows the user to specify an installation directory.
Fixes #243
> #243 per-user-install and directory selection activated for Windows-MSI installer

- .github/workflows/kit.yml
- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
Use Java 16 to build and release Scene Builder
> Update release workflows to use Java 16

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/DialogListItemComparator.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/LibraryDialogController.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/DialogListItemComparatorTest.java
The Library Manager ListView is now backed by a SortedList.
A specific comparator class has been created which puts directories at first, then files, then Maven coordinates.
The sorting on files is performed with Path.compare() and for Maven coordinate comparison String comparison is used.
For the sake of testing, a resource (empty file serving as jar) has been added. With that it can be ensured that the test works on an existing file and existing folder, so that the behaviour of folders first/then files/then Maven coordinates can be tested.
> The Library Manager ListView is now backed by a SortedList.

- app/pom.xml
- kit/pom.xml
Fixes some warnings during the Maven build process:
```
$ mvn clean package
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.gluonhq.scenebuilder:kit:jar:16.0.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-jar-plugin is missing. @ line 105, column 21
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for com.gluonhq.scenebuilder:app:jar:16.0.0-SNAPSHOT
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of …
```
> Fix some Maven compile warnings

- README.md
Updated Readme.md in order to provide correct instruction how to run Scene Builder using Maven.
Fixes #348
> Updated instruction in README how to execute Scene Builder using Maven.

- .github/scripts/jpackage.bat
SceneBuilder does not start on Windows, when another JDK with conflicting runtime components is installed on the users system.
Added --java-options to limit scope of effective 'java.library.path' to the options of the `jpackage.bat` file.
I have tested the modified package process on Windows 10 with also having the issue reproduced upfront.
Next step would be to repeat the test in Linux.
Fixes #344 for Windows 10
> Added --java-options to limit scope of effective 'java.library.path' to bundled runtime.

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/AbstractSkeletonCreator.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBuffer.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonContext.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonCreator.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonCreatorJava.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonCreatorKotlin.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonSettings.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonWindowController.java
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonWindow.fxml
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/JfxInitializer.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMSaverUpdateImportInstructionsTest.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/StaticLoadTest.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/EmptyController.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/NestedClassController.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferJavaTest.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferKotlinTest.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferTest.java
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/Test.fxml
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/TestNested.fxml
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_java_comments.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_java_full.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_java_full_comments.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_java_nested.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_kotlin_comments.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_kotlin_full.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_kotlin_full_comments.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_kotlin_nested.txt
Adds support to create a skeleton for Kotlin.
A major refactoring of the SkeletonBuffer was necessary:
- split up into "construct" phase (SkeletonBuffer, which constructs a context for SkeletonCreator) and "create" phase (SkeletonCreator)
- create phase has no side-effects (everything is now determined from the given input)
- Kotlin and Java are two different create-phases
- added tests that validate the whole skeleton (until now only the "package" line was validated for Java)
- more tests verifying the whole skeleton could be added easily (e.g. for Java, too)
Fixes #259
> feat: Add support for controller skeletons in Kotlin

- .github/release-drafter.yml
- .github/workflows/build.yml
Automates release notes from PR. Each time a PR is merged into the master branch, it is added to the release notes in Github Release.
Example: https://github.com/gluonhq/substrate/releases
> Add release drafter

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/AbstractSkeletonCreator.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonContext.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonCreatorJava.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonCreatorKotlin.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/eventnames/ImportBuilder.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferTest.java
Fixes the broken tests for FXML controller sekeleton creation on Windows. 
Root cause was a hard coded `\n` in `ImportBuilder` class. The job of creating import lines for Kotlin and Java is now delegated to AbstractSkeletonCreator subclasses.
Fixes #376
> AbstractSkeletonCreator subclasses create now consistent line endings.

- .github/workflows/build.yml
- README.md
- checkstyle.xml
- pom.xml
The [Checkstyle](https://checkstyle.org) [Maven Plugin](https://maven.apache.org/plugins/maven-checkstyle-plugin/index.html) has been added to the main `POM.xml` to enable creation of a code style report.
A very basic configuration is provided as well, which primarily checks for extra whitespace, empty lines and empty blocks.
This plugin is not yet executed during build.
Fixes #397
> Added checkstyle plugin to main POM.xml with basic config.

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileNameProposal.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileWriter.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileWriterErrorAlert.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileWriterSuccessAlert.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonSettings.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonWindowController.java
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/alert/Alert.css
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit_ja.properties
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonWindow.fxml
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/skeleton/clipboard-copy-icon.svg
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileNameProposalTest.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileWriterTest.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonSettingsTest.java
The functionality is now as follows:
* The controller skeleton preview as now a "Save as" button.
* When pressed a file name is proposed.
* When confirmed with "save", the skeleton is saved to the proposed file.
* A confirmation dialog is shown, which allows to copy the file path to the clipboard.
Following use cases have been explored (the following examples refer to Java but this works with Kotlin as well):
| # | Use case | FXML status | Controller class definition | File Name Proposal |
|-|-|-|-|-|
| 1 | Fresh project | FXML not saved | not specified                           |  `~/PleaseProvideControllerClassName.java` |
| 2 | Fresh project | FXML not saved | set to `MyCustomController`  |  `~/MyCustomController.java` |
| 3 | Fresh project | FXML saved (e.g. …
> Added a "save as" function for the controller skeleton preview.

- .github/release-drafter.yml
Release drafter is used to automatically create release notes for Scene Builder. Since we have quite a few changes for 17, it is a good idea to categorize them.
All PRs are now labelled as either 'enhancement' or 'bug' . We use these labels against these PRs to group them into 'Features' and 'Bug Fixes' in the release notes.
> release-drafter: categorize changes

- .github/scripts/jpackage.sh
- .github/workflows/linux.yml
- app/src/main/java/com/oracle/javafx/scenebuilder/app/about/AboutWindowController.java
- app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp.properties
In some cases, due to library path pollution by old JDK/JavaFX installations, startup of Scene Builder after installation from DEB or RPM package will fail. Thus, instead going with default `java.library.path` setting, a custom `java.library.path` is provided in the `jpackage.sh` script file.
The text in the About dialog has been updated in order to show effective `java.library.path` configuration (incl. configured but missing or invalid directories). The dialog text shows only normalized absolute paths.
Fixes #362
> Custom 'java.library.path' for Linux packages to avoid startup issues

- .github/scripts/repackage-deb.sh
- .github/workflows/linux.yml
- app/assets/linux/SceneBuilder.desktop
There is now a custom `SceneBuilder.desktop` file inside `app/assets/linux` directory and the Linux workflow provides the argument `--resource-dir app/assets/linux` to the `jpackage.sh` script.
With that, the package process will use the .desktop template which now also provides the `StartupWMClass` setting.
Unfortunately there seems to be no placeholder such as `MAIN_CLASS` at this point, hence the main class is hardcoded in the .desktop file.
This works for DEB and RPM.
```ini
[Desktop Entry]
Name=APPLICATION_NAME
Comment=APPLICATION_DESCRIPTION
Exec=APPLICATION_LAUNCHER
Icon=APPLICATION_ICON
Terminal=false
Type=Application
Categories=DEPLOY_BUNDLE_CATEGORY
DESKTOP_MIMES
StartupWMClass=com.oracle.javafx.scenebuilder.app.SceneBuilderApp
```
Fixes #359
> Fix app name on Ubuntu

- .github/workflows/linux.yml
- app/assets/linux/SceneBuilder.desktop
Added a main category and multiple additional categories to the desktop entry template.
Fixes #58
> Categories for Linux desktop entry

- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
Remove app-version input from bundles-kit.yml invocation
Issue
Early-access workflow is broken due to an unrecognized input
> Fix early-access GH workflow

- .github/workflows/bundles-mac.yml
The PR fixes the Jpackage step where it fails to find a keychain to sign the bundle.
Fixes #499
> Fix typo in jpackage job

- pom.xml
Use JavaFX 18 instead of 18-ea+12
This closes #529
We are still using JavaFX 18-ea+12
> build: Use JavaFX 18

- .github/workflows/bundles-kit.yml
> build: Use Xvfb display in kit-bundle workflow

- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/JobManagerTest.java
> test: Added JobManagerTest

- app/src/main/java/com/oracle/javafx/scenebuilder/app/menubar/MenuBarController.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/tracking/Tracking.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/util/AppSettings.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/util/MessageBox.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/content/ContentPanelController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/content/mode/EditModeController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/css/CssPanelController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/css/CssUtils.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/inspector/editors/PropertyEditor.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/i18n/I18NControl.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/LibraryItem.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/UserLibrary.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/MetadataIntrospector.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/ReflectionUtils.java
> refactor: Replaced print stack trace calls with Logger

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/LibraryListCell.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/BuiltinLibrary.java
There is a FX8 qualifier for controls in the built-in library.
All these FX8 controls are unique, there are no FX2 or other derivatives.
Fixes #586
> fix: Removed FX8 qualifier in built-in library

- app/src/main/java/com/oracle/javafx/scenebuilder/app/welcomedialog/WelcomeDialogWindowController.java
Disabled mnemonic parsing on RecentDocumentsButtons on Welcome Page in oder to have correct file name rendering for filenames with underscores. 
Fixes #572
> fix: Filenames with underscores are rendered incorrectly on Welcome Page

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/AbstractSkeletonCreator.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonConverter.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonCreator.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonCreatorJRuby.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonFileNameProposal.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonSettings.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/skeleton/SkeletonBufferJRubyTest.java
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_ruby_comments.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_ruby_full.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_ruby_full_comments.txt
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/skeleton/skeleton_ruby_nested.txt
Adds JRuby as a language to the controller skeleton dialog. Note that JRuby doesn't need the fields, as JRubyFX inserts all of them automatically, this is principally for the methods/callbacks, and field reference.
Based on discussion #595
> feat: Add JRuby controller skeleton generation

- checkstyle.xml
Added OperatorWrap rule to Checkstyle so that unwrapped operators are no longer an issue in PRs.
Fixes #620
> build: Added OperatorWrap rule to Checkstyle

- pom.xml
@abhinayagarwal 
Fixes #620 
As discussed, the Checkstyle plugin is now configured to verify test sources formatting as well.
> build: Checkstyle is applied to test sources

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/HeaderWithNotOnlyImports.fxml
- pom.xml
Updated Github Actions Workflows to use JavaFX 20 and Java 20.
Fixes #617
The workflows did not run yet, so it can happen that for the one or other workflows errors occur. I will run tests locally on Ubuntu and Windows accordingly, Mac test only for x86.
> build: Use Java and JavaFX 20

- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
Fixed logging file, which previously only worked from an IDE / local run outside of a JAR. This bug was introduced in 2021; https://github.com/gluonhq/scenebuilder/pull/371. The approach (setting a file property) did not work, as the JDK's LogManager failed to find the file -- inside a jar -- and silently fails (frustratingly), resulting in no logging config at all. That is not how that property is intended to be used (an external file is assumed as FileInputStream is used). Another approach that would work is to use java.util.logging.config.class and specify a class (with the job of setting properties). This fix is a shortcut to basically do the same thing.
No logging file was created nor logged to.
Fixes #661 
As per commit message.
> fix: logging file creation from jars and package

- README.md
**Summary:**
This PR updates SceneBuilder's documentation, renaming the generated folder from 'kit' to 'app' for clarity. The changes, made in English, aim for consistency and improved user understanding. Ready for review and merging. 🚀
Fixes #668
> docs: rename chekstyle for app from kit to app

- .github/workflows/bundles-mac_aarch64.yml
> build: replace self-hosted runner with default m1 runners

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- pom.xml
As OpenJFX 22 was release, SceneBuilder can use the new version.
This PR consists yet of 2 commits. 1 change include the reactor POM.xml with the latest OpenJFX version. The other one updates all Github workflows.
Fixes #685
> build: Use Java and JavaFX 22

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- pom.xml
Scene Builder EA should be able to use EA version of Java/FX.
Also update build to use 23-ea
Fixes #706
> build: Use Java and JavaFX 23-ea

- checkstyle.xml
Added rule to check that line length in Java files not exceeds 120 chars.
Fixes #690 
With the new checkstyle rule, one will now get warnings on overly long lines:
```
> mvn checkstyle:checkstyle
...
[WARN] PreferencesRecordDocument.java:134: Zeile ist 121 Zeichen lang (Obergrenze ist 120). [LineLength]
[WARN] PreferencesRecordDocument.java:156: Zeile ist 148 Zeichen lang (Obergrenze ist 120). [LineLength]
[WARN] PreferencesRecordGlobal.java:418: Zeile ist 125 Zeichen lang (Obergrenze ist 120). [LineLength]
[WARN] PreferencesRecordGlobal.java:423: Zeile ist 129 Zeichen lang (Obergrenze ist 120). [LineLength]
...
```
> build: Checkstyle now verifies line length of Java files (<=120 char)

- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- pom.xml
> build: artifact with this name already exists failure fix

- README.md
- pom.xml
> Lower required Java level to 21

- app/pom.xml
- kit/pom.xml
- pom.xml
Bumps snapshot version number from 23.0.0-SNAPSHOT to 24.0.0-SNAPSHOT
Fixes #723
> build: incremented version number to snapshot of next major release

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/control/paintpicker/PaintPickerController.java
The constructor of the PaintPickerController class must be public so that construction via FXML declaration will work.
Fixes #731
> fix: Constructor is now public (required for instantiation via FXML, issue 731).

- .github/scripts/jpackage.bat
- .github/scripts/jpackage.sh
As with JLink 21 the option `--compress 2` is deprecated, `--compress zip-9` is used instead.
Fixes #741
> build: Replaced deprecated --compress 2 option with new JLink 21 compliant --compress zip-9

- LICENSE.txt
Copyright year of license.txt is outdated.
Fixes #740
> docs: Updated license copyright year to 2024

- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit_ja.properties
Add missing Japanese translations.
Fixes #734
See also PR #746
> feat: added missing Japanese translations

- app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp_zh_CN.properties
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit_zh_CN.properties
adding missing Chinese translations and correcting some existing ones.
Fixes #
> feat: added missing Chinese translations

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- app/pom.xml
- kit/pom.xml
- pom.xml
After quarterly release of Java and JavaFX 23.0.1, build Scene Builder 23.0.1, branching out from 23 tag, including workflow fix to build Scene Builder for macOS Intel.
> Scene Builder 23.0.1

- app/pom.xml
- app/src/main/java/com/oracle/javafx/scenebuilder/app/DocumentWindowController.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/util/AppSettings.java
- app/src/main/java/module-info.java
- kit/pom.xml
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/manager/LibraryDialogController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/MavenDialogController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/MavenRepositorySystem.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/repository/RepositoryManagerController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/repository/dialog/RepositoryDialogController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/search/MavenSearch.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/search/NexusSearch.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/search/SearchMavenDialogController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoader.java
- kit/src/main/java/module-info.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/fxom/FXOMLoaderTest.java
- pom.xml
Fixes #757
Before this PR, when running the application, Maven warns about:
```
[WARNING] *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [aether-api-1.1.0.jar, aether-impl-1.1.0.jar, aether-spi-1.1.0.jar, aether-util-1.1.0.jar, aether-connector-basic-1.1.0.jar, aether-transport-file-1.1.0.jar, aether-transport-http-1.1.0.jar, maven-aether-provider-3.3.9.jar, …
```
> feat: Remove/Update Kit third-party dependencies

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/content/ContentPanelController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/content/WorkspaceController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/preview/PreviewWindowController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/CssInternal.java
to prevent user agent from being overwritten
This PR removes the platform stylesheet from the theme in content/preview, which is modena.css, since it is already added to Scene Builder, preventing the user agent stylesheets from external controls in the custom library to be overwritten.
This was only working before #745 and #720 by an underlying bug (modena.bss was used to create an invalid URL and the real modena.css URL was never added to the theme stylesheets. 
Fixes #760
> fix: Remove platform theme url from stylesheets, 

- .github/workflows/early-access.yml
- gluon-plugin/pom.xml
- kit/pom.xml
- pom.xml
Fixes #749
This is still somehow work in progress, therefore it only has the deploy call from the early-access job, to test if everything works deploying to Sonatype.
> feat: publish Kit snapshot to sonatype

- .github/workflows/early-access.yml
> fix: Deploy locally before releasing with JReleaser

- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/css/ThemeDark.css
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/css/ThemeDefault.css
Fixes #773 
The hierarchy panel (a `StackPane`) needs to set the padding to 0 as well, otherwise, when using Scene Builder Kit from an external application, modena default padding:
```
.titled-pane > .content > StackPane,
...
.titled-pane > .content > VBox {
-fx-padding: 0.8em;
}
```
is set for the pane.
> fix: add missing css rule to hierarchy panel

- app/src/main/resources/logging.properties
Fixes #782
Even for releases, I'd say we keep the console handler, as running from the installer won't show a terminal window. But if users/developers need it, they still can run the executable from a terminal.
> add consoleHandler

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/inspector/InspectorPanelController.java
Fixes #771
Using the inspector menu button to select view modes, the accordion panes are removed and added, based on selection. There is an instant where the `accordion.getExpandedPane()` value is null, and that should be filtered out from the switch expression in `InspectorPanelController::expandedSectionChanged`
> fix: Fix NPE in accordion

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/inspector/editors/StyleEditor.java
Fixes #774
The css expression `propertyVal + ": " + valueVal + ";"` only makes sense if _both_ property and value are not empty. This fix prevents an unnecessary parsing call that derives in uncaught CSS warnings.
> fix: Prevent css parsing if any style textfield is empty

- app/src/main/java/com/oracle/javafx/scenebuilder/app/menubar/MenuBarController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorController.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/content/ContentPanelController.java
Fixes #764
When the swatch color property changes, the list of external stylesheets applied to the current theme changes too, so the editorController needs to make another call to retrieve those, if any (for instance, when the Gluon plugin is present), and refresh content/preview/... accordingly
> fix: Force refresh of theme and stylesheets when swatch color changes

- .github/scripts/jpackage.bat
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/fxom/HeaderWithNotOnlyImports.fxml
- pom.xml
Fixes #794, by adding flag that enables reading the FXML file with javascript language. Also reverts a small change done in #619, as now the test as it was before passes.
Important note: Scene Builder (workspace/preview) does not evaluate the onAction eventHandlers, so there is no need for a Nashorn engine, and there is no risk of opening any FXML file with any kind of malicious script.
> build: Allow importing FXML files with javascript

- .github/workflows/early-access.yml
- .github/workflows/release.yml
A test run is available [here](https://github.com/abhinayagarwal/scenebuilder/actions/runs/13366022942) which builds with 23.0.2 (latest) released GA version.
Fixes #801
> build: use latest release to avoid workflow failure
