gluonhq/scenebuilder

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/property/value/ButtonTypePropertyMetadata.java
Fix #174
Add Button type "OK" to ButtonTypePropertyMetadata.
ButtonType class has OK field, So It should support ButtonType "OK".
https://docs.oracle.com/javase/jp/8/javafx/api/javafx/scene/control/ButtonType.html
> Issue #174: Add Button type "OK"

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
This PR allows the project to be built and run with Java 11.
> Integration with Java 11

- app/src/main/java/com/oracle/javafx/scenebuilder/app/welcomedialog/WelcomeDialogWindowController.java
This PR fixes menu-bar on Linux machines for JDK 8. Also fixes the bug which constraint the main window from resizing. 
This was already fixed in JDK 9 as a part of [JDK-8152421](https://bugs.openjdk.java.net/browse/JDK-8152421).
Fixes #145 #173
> Fix Menu Bar interaction on Linux for SB 8

- app/build.gradle
- build.gradle
- kit/build.gradle
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/preset/MavenPresets.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/search/NexusSearch.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/maven/search/SearchService.java
Updates all http nexus links with https
> Update all http://nexus.gluonhq.com occurences to HTTPS

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/glossary/ControllerClass.java
Migrated from bitbucket, plus removed sysouts (sorry for that)
> Scan test resources for controller class

- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
gradlew build instructions doesn't work with java 13 (says incompatible version 57). Also, shadow plugin version is very old and also says that it's incompatible with java13.
I've upgrade gradlew, shadow plugin and javafx plugin to latest versions and it's works
> Gradle Java 14 compatibility 

- app/src/main/java/com/oracle/javafx/scenebuilder/app/AppPlatform.java
> Fix first time startup issue on notarized SceneBuilder on mac

- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
GA can now release candidates before actual release.
> GA: Add functionality to release RCs

- .github/workflows/kit.yml
SB kit jar is uploaded when repository is tagged
> SB Kit Jar should be a part of the release

- .github/workflows/kit.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
- .gitignore
This PR fixes failing GA workflows
> Fix failing GA workflows

- LICENSE.txt
> Update License header year to 2021

- .github/workflows/linux.yml
Fix path for uploading artifacts from Linux GA workflow
> Fix S3_PATH for linux artifacts

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/pull_request_template.md
> Add templates for issues and PR

- .github/workflows/release.yml
- app/src/main/java/com/oracle/javafx/scenebuilder/app/util/AppSettings.java
- version.json
Uploads `settings.properties` and `version.json` as a part of the release workflow
Fixes # 329
> Upload files as a part of release workflow

- .github/workflows/kit.yml
- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
Update SB release workflow for 16
> Prepare Scene Builder 16 release

- .github/workflows/release.yml
Add AWS credentials as environment variables
> Fix AWS S3 upload

- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
Fixes a potential NPE in update check
> Avoid potential NPE

- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
> Skip update check in developer mode

- app/src/main/java/com/oracle/javafx/scenebuilder/app/AppPlatform.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/about/AboutWindowController.java
- app/src/main/resources/logging.properties
> Load logging configuration in Application class

- .github/workflows/build.yml
> Run tests on all OS

- app/src/main/java/com/oracle/javafx/scenebuilder/app/UpdateSceneBuilderDialog.java
- app/src/main/resources/com/oracle/javafx/scenebuilder/app/css/UpdateSceneBuilderDialog.css
Fix truncated labels in Update Dialog on Linux
Fixes #333
> Fix truncated text in Update dialog

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java
This PR fixes #386.
FileSystemWatcherService is stopped on a finally block.
> Fix for issue #386

- .github/workflows/build.yml
- .github/workflows/kit.yml
- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
- app/pom.xml
- kit/pom.xml
- pom.xml
Updates Maven and GA to:
* SB: 17.0.0
* JavaFX: 17
* Java: 17-ea
Also, move from AdoptOpenJDK to Temurin
> Prepare SB 17

- .github/workflows/kit.yml
- .github/workflows/linux.yml
- .github/workflows/mac.yml
- .github/workflows/win.yml
Use OpenJDK for creating Scene Builder bundles
> Use OpenJDK binaries

- pom.xml
> Fix URL for issue management

- app/pom.xml
- app/src/main/java/com/oracle/javafx/scenebuilder/app/about/AboutWindowController.java
> Show Java version and runtime name in About Dialog

- CONTRIBUTING.md
> Added initial draft of contribution workflow

- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
@Oliver-Loeffler this is a simple refactor, but please double check all is fine
> refactor logTimestamp()

- app/src/main/java/com/oracle/javafx/scenebuilder/app/DocumentWindowController.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
Contributes to #445 
Another simple refactor, @Oliver-Loeffler please review when you get a chance.
> refactor public API to return Optional instead of null

- kit/pom.xml
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/EditorPlatform.java
- pom.xml
> Update Glisten dependencies

- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/menubar/MenuBarController.java
- app/src/main/java/com/oracle/javafx/scenebuilder/app/registration/RegistrationWindowController.java
- app/src/main/resources/com/oracle/javafx/scenebuilder/app/i18n/SceneBuilderApp.properties
- app/src/main/resources/com/oracle/javafx/scenebuilder/app/menubar/MenuBar.fxml
Prevents the registration window from automatically popping up randomly at launch and adds a manual registration trigger to the help menu.
Fixes #448
> Moves registration trigger to a help menu item.

- .github/workflows/build.yml
Bringing back previously removed `build.yaml` with following changes:
- Executed on PR only for ALL branches.
- Draft release step is removed
As discussed in #504
> build: Add workflow for PR checks

- LICENSE.txt
> docs: Updated license to 2022

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/BuiltinLibrary.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/UserLibrary.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/library/BuiltinLibraryTest.java
- refactor Library to avoid accessing fields directly
- add initial test
> refactor: Cleaned up Library

- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/template/Template.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/template/TemplateTest.java
> refactor: Removed null field and logic from Template enum

- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/job/DeleteObjectJobTest.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/job/RelocateSelectionJobTest.java
- kit/src/test/resources/com/oracle/javafx/scenebuilder/kit/editor/job/basic.fxml
> test: Added DeleteObject and RelocateSelection job tests

- pom.xml
This is the penultimate PR to go into SB18. After the EA build for this is ready, we switch to the new (SB18) branch and keep this  for testing purposes until javafx 18 arrives, at which point we make the 18 release.
Fixes #431 
Addresses preparations for #525 ea testing
> build: Java 11 -> 17, JavaFX 17 -> 18-ea+12

- pom.xml
> build: JavaFX 18-ea+12 -> 18 (#530)

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
> build: Use Java/JavaFX version 18

- app/pom.xml
- kit/pom.xml
- pom.xml
> build: Prepare version for release

- app/pom.xml
- kit/pom.xml
- pom.xml
> build: Restore SNAPSHOT version

- .github/workflows/release.yml
> build: Use workflow from current repository

- .github/workflows/release.yml
> build: Rollback change in release workflow

- .github/workflows/early-access.yml
- .github/workflows/release.yml
Update release workflow according to https://github.com/gluonhq/scenebuilder/discussions/525
> build: Update release workflow to explicitly set version before release

- .github/workflows/release.yml
> build: Set release version, but without commit to master

- pom.xml
Fixes failure in release step
https://github.com/gluonhq/scenebuilder/actions/runs/2066989129
> build: update jreleaser plugin in pom.xml

- app/pom.xml
- kit/pom.xml
- pom.xml
> build: Bump to 19-SNAPSHOT

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
> build: Use Xvfb display

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
> build: use Java/FX 19

- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
> Use different keychain on every run, rename artifact

- app/pom.xml
- kit/pom.xml
- pom.xml
Updated Scene Builder version in POM.xml files.
Fixes #597
> build: incremented version to 20.0.0-SNAPSHOT.

- LICENSE.txt
Update license year
Fixes #611
> docs: Update year to 2023

- app/src/main/java/com/oracle/javafx/scenebuilder/app/SceneBuilderApp.java
Code maintenance
Relates to #445
> refactor: Remove outdated comments, clean up code

- app/pom.xml
- kit/pom.xml
- pom.xml
> build: increment version to 21.0.0-SNAPSHOT

- pom.xml
> build: use JavaFX 21-ea for testing

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- pom.xml
> Use JDK and JavaFX 21

- .github/workflows/bundles-mac.yml
> build: notarize action update

- .github/workflows/release.yml
> build: add input to release workflow

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- app/pom.xml
- kit/pom.xml
- pom.xml
> build: use Java and JavaFX 21.0.1

- .github/workflows/bundles-mac_aarch64.yml
> build: update notarization on mac-aarch64 builds

- app/pom.xml
- kit/pom.xml
- pom.xml
Update development version after release of v21.0.1
> build: increment version to 21.0.2-SNAPSHOT

- .github/workflows/bundles-windows.yml
> build: disable signing windows bundle

- app/pom.xml
- kit/pom.xml
- pom.xml
Update development version after release of v21.0.1
> build: increment version to 22.0.0-SNAPSHOT

- app/pom.xml
- kit/pom.xml
- pom.xml
Update development version after release of v22.0.1
> build: increment version to 22.0.1-SNAPSHOT

- .github/workflows/early-access.yml
- .github/workflows/release.yml
> build: use relative path for resuesable workflows in same repository

- app/pom.xml
- kit/pom.xml
- pom.xml
Update development version to `23.0.0-SNAPSHOT`
> build: increment version to 23.0.0-SNAPSHOT

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
> update actions to use latest versions

- kit/pom.xml
- kit/src/main/java/module-info.java
- pom.xml
> fix: Add missing module to kit and update versions

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/util/CssInternal.java
> feat: Remove deprecated API from JavaFX 23

- .github/workflows/bundles-mac.yml
Run workflow on macOS-13 for Intel build
Fixes #735
> build: Update bundles-mac.yml

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- pom.xml
> bump JDK and JavaFX versions

- .github/workflows/early-access.yml
> update early access job

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- pom.xml
Cherry picked commits from master to prepare release of Scene Builder 23.0.1 from release branch `23.0.1`
> Prepare for release 23.0.1

- app/pom.xml
- kit/pom.xml
- pom.xml
Sets the release version for release branch 23.0.1
> Set release version

- pom.xml
> Don't release checksum and signature files

- .github/workflows/release.yml
> fix: Add deploy step to release job

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/panel/library/LibraryUtil.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/user/LibraryFolderWatcher.java
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/library/util/ModuleExplorer.java
- kit/src/main/resources/com/oracle/javafx/scenebuilder/kit/i18n/SceneBuilderKit.properties
> feat: Add ModuleExplorer to explore custom controls in modules

- app/src/main/java/module-info.java
- kit/src/main/java/module-info.java
> fix: add optional modules to kit

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/metadata/Metadata.java
> fix: Restore back removed metadata for DialogPane

- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/preview/PreviewWindowController.java
> fix: Update PreviewWindowController to prevent exception

- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
> build: Update apple action version

- .github/workflows/release.yml
> build: Add input for RC version to release workflow

- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
> build: update ubuntu to v24.04

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- kit/src/main/java/com/oracle/javafx/scenebuilder/kit/editor/DocumentationUrls.java
- kit/src/test/java/com/oracle/javafx/scenebuilder/kit/editor/DocumentationUrlsTest.java
- pom.xml
> Bump JavaFX version to 24

- .github/workflows/build.yml
- .github/workflows/bundles-kit.yml
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- .github/workflows/bundles-windows.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
> Remove default Java version from bundles jobs

- .github/scripts/jpackage.bat
- .github/workflows/bundles-linux.yml
- .github/workflows/bundles-mac.yml
- .github/workflows/bundles-mac_aarch64.yml
- pom.xml
also: remove deprecated options
Fixes #819
> build: Add Java options to prevent warnings running JDK24+

- app/pom.xml
- gluon-plugin/pom.xml
- kit/pom.xml
- pom.xml
> build: prepare next development version

- .github/workflows/build.yml
- .github/workflows/early-access.yml
- .github/workflows/release.yml
- README.md
- app/pom.xml
- gluon-plugin/pom.xml
- kit/pom.xml
- pom.xml
> build: prepare Scene Builder 25 release
